version: '3.8'

services:
  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    restart: unless-stopped

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5052:5052"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
